### ISSUE TITLE
Phân công vai trò

### ISSUE THREAD

**Issue by VuDinhDuy** [VuDinhDuy/CNPM_BaiTapLon#1]

**Comment by dangvietvu** [comment]
Đặng Việt Vũ: Developer

**Comment by manhcuong800** [comment]
Đàm Mạnh Cường: Developer

**Comment by VuDinhDuy** [comment]
Vũ Đình Duy: SCRUM Master

**Comment by manhquyen161996** [comment]
Đỗ Mạnh Quyền: Developer

**Comment by dangvietvu** [comment]
Developer

Vào 13-10-2017 1:11 CH, "VuDinhDuy" <notifications@github.com> đã viết:
