### ISSUE TITLE
Thông báo: Họp bàn kế hoạch ngày 16/12

### ISSUE THREAD

**Issue by VuDinhDuy** [VuDinhDuy/CNPM_BaiTapLon#12]
Chiều ngày 16/12 mọi người tập trung để thảo luận, thống nhất những vấn đề chung, đồng thời trao đổi về cách thức thực hiện cụ thể với từng công việc mà mỗi người được giao nhé.
Sau đó, khi đã hiểu rõ quy trình, chúng ta sẽ đẩy nhanh tiến độ, mỗi người nhanh chóng hoàn thành phần việc của mình, để dự kiến 22/12 trang web sẽ cơ bản được hoàn thiện. Thời gian sau đó chỉ là chỉnh sửa những chi tiết cuối cùng.

**Comment by manhquyen161996** [comment]
ok.ae nhớ đi đầy đủ nhá

**Comment by manhcuong800** [comment]
OK. chốt chiều hôm đó a-e tập trung cụ thể

**Comment by manhquyen161996** [comment]
nhanh nhanh còn ôn môn khác

**Comment by dangvietvu** [comment]
Oke.còn nhiều vấn đề muốn hỏi mn cho rõ.

**Comment by VuDinhDuy** [comment]
Quyền nhanh chóng ghi lại biên bản cuộc họp nhé, tạo một issue mới để viết.
