### ISSUE TITLE
Kết quả cuộc họp ngày 16/12

### ISSUE THREAD

**Issue by manhquyen161996** [VuDinhDuy/CNPM_BaiTapLon#15]
1. Chốt được theme của trang web: FlowNews
2. Domain: tuoitretuonglai.cf
Host Wordpress: z.com 
3. Xây dựng và tuỳ chỉnh giao diện (Vũ thực hiện): Header (menu, banner, logo), Footer (thông tin chi tiết, địa chỉ liên hệ), Body (vùng hiển thị các bài đăng, sidebar)
4. Thống nhất các tính năng của trang web (Cường thực hiện):
* Phát triển các tính năng sẵn có của theme:
   - Dùng WPBakery Page Builder hỗ trợ xây dựng giao diện cùng Vũ;
   - Tạo các widget cho sidebar và footer;
   - Tuỳ biến cho theme bằng tính năng Customize;
   - Tạo các chuyên mục bài viết;
   - Thiết lập những chi tiết khác cho web như permalink, reading, writing, comment...
* Cài đặt các plugin hỗ trợ bổ sung:
   - TinyMCE Advanced: Bổ sung các công cụ soạn thảo;
   - WP Smush: Tối ưu hình ảnh tải lên;
   - Yoast SEO: Tối ưu SEO cho các bài viết và trang;
   - WP Optimize: Dọn rác & tối ưu database.
5. Thống nhất lịch trình tiếp theo:
https://github.com/VuDinhDuy/CNPM_BaiTapLon/projects/1#card-6248807

**Comment by dangvietvu** [comment]
Mọi người chuẩn bị về nội dung trang web cho phong phú nhé.Duy sẽ phân công về nội dung ^^

**Comment by manhcuong800** [comment]
Cho các bài viết chỉnh sửa theo font chữ và căn lề như đã định. Lấy ảnh tiêu đề 642-876 nhé mức này t thấy khá đẹp và cân xứng
