### ISSUE TITLE
Bước 1: Thu thập thông tin

### ISSUE THREAD

**Issue by VuDinhDuy** [VuDinhDuy/CNPM_BaiTapLon#4]

**Comment by dangvietvu** [comment]
Tham khảo giao diện và cách hoạt động của các trang web lớn tương tự

**Comment by VuDinhDuy** [comment]
Hiểu được nội dung, yêu cầu mà một trang báo điện tử cần phải có.
Tìm kiếm, tham khảo những ý tưởng về việc lập trang web báo điện tử: những chủ đề thông tin, đối tượng phục vụ, bố cục trang, khả năng sử dụng tiện lợi (cho cả chủ sở hữu, người viết và độc giả), ...

**Comment by VuDinhDuy** [comment]
Như yêu cầu đặt ra từ trước, đây là trang web báo điện tử chủ yếu hướng đến đối tượng người đọc là những thanh thiếu niên, vì vậy những nội dung thông tin cần có là: 
1. Công nghệ
2. Xã hội
3. Thể thao
4. Giáo dục
5. Văn hoá, lối sống
6. Sức khoẻ
7. Người nổi tiếng
8. Giải trí, chuyện lạ
9. Game
10. Tin tuyển dụng

Nguồn thông tin sẽ là những trang báo uy tín ở trong và ngoài nước, hoặc từ hiểu biết của người viết.
