### ISSUE TITLE
Bước 2: Phân tích và lập kế hoạch

### ISSUE THREAD

**Issue by manhquyen161996** [VuDinhDuy/CNPM_BaiTapLon#5]

**Comment by VuDinhDuy** [comment]
Quyền bắt đầu phân tích và lên kế hoạch nhé. 
Web của mình dựa trên nền tảng Wordpress, vậy nên tìm kiếm một hosting Wordpress đi. 
Sau đó lên ý tưởng về bố cục, phối màu, trang trí giao diện... Không chỉ cần đẹp mà còn lưu tâm đến góc nhìn của người xem nữa, phải làm sao để bắt mắt, thuận tiện cho họ sử dụng.
Suy nghĩ về những plug-in nào sẽ cần thiết để tạo thêm tính năng cho web, ví dụ như hỗ trợ cho việc SEO, search bài viết, soạn thảo, ...

Tham khảo quy trình thiết kế web của một số công ty: 
http://trivietit.net/quy-trinh-thiet-ke-website.html
https://osv.vn/quy-trinh-thiet-ke-website/
http://khoweb.vn/phan-tich-ke-hoach-cho-website

**Comment by manhcuong800** [comment]
cụ thể là mk sẽ tách thành nhiều file PHP header footer rồi các content thẻ trong đó để dễ dàng quản lý hơn

**Comment by manhcuong800** [comment]
tại wordrpress nó có hàm get_footer(); là nó upload được cái file footer.php tách ra rồi a-e dễ xữ lý hơn là để mã HTML quá nhiều vào trong 1 cái plugin trong wp

**Comment by manhquyen161996** [comment]
ok

**Comment by VuDinhDuy** [comment]
Quyền nhanh chóng chốt ý tưởng về giao diện sẽ sử dụng nhé.

**Comment by dangvietvu** [comment]
Dù sao nộ dung cũng là quan trọng hơn hết. Content is King mà :)

**Comment by manhquyen161996** [comment]
Sau một thời gian suy nghĩ thì tôi có một số ý tưởng về trang web tin tức của chúng ta như sau:
1. Thứ nhất về tên trang sẽ là tuoitretuonglai và vì dùng host free nên sẽ có đuôi là .tk.
2. Thứ 2 là về giao diện:
- Trang web sẽ có màu nền là màu trắng cho dễ nhìn và theo dõi.
- Sẽ có 3 phần chính là Header, Content, và phần Footer.
- Phần Header sẽ bao gồm Banner và phần menu.
- Phần Content của chúng ta sẽ chứa các bài viết tin tức và chủ yếu sẽ chia thành 3 cột.
- Phần Footer sẽ là thông tin liên hệ như sđt, địa chỉ, liên kết Facebook, mail, twitter, . . . để giải đáp thắc mắc.
* Đó là một số những ý tưởng chính về trang web của chúng ta. Đến khi thực hiện sẽ không tránh khỏi các vấn đề phát sinh, lúc đấy chúng ta sẽ cùng tìm cách giải quyết.
Mn thấy không ổn ở đâu hay cần góp ý chỗ nào thì cứ vào bàn luận nha.
