### ISSUE TITLE
Bước 3: Thiết kế

### ISSUE THREAD

**Issue by manhquyen161996** [VuDinhDuy/CNPM_BaiTapLon#6]

**Comment by VuDinhDuy** [comment]
Thực hiện: Đặng Việt Vũ

**Comment by dangvietvu** [comment]
Sử dụng bootstrap thiết kế giao diện Front end

**Comment by manhcuong800** [comment]
google getbootrap tải về rồi ném vào project

**Comment by manhcuong800** [comment]
thực chất bootrap cũng hỗ trợ nhiều các chức năng đấy

**Comment by VuDinhDuy** [comment]
Chuẩn bị tìm hiểu về việc thiết lập, tuỳ chỉnh cho theme Wordpress đi nhé Vũ. Đã từng làm web Wordpress nào chưa?

**Comment by dangvietvu** [comment]
T cũng đã từng làm một trang wordpress rồi nhưng ở mức độ đơn giản thôi chưa làm một trang giao diện chuyên nghiệp bao giờ.

**Comment by dangvietvu** [comment]
Ngày kia (16/12) nhóm mình tổ chức họp nhé.Bàn bạc cho chi tiết để xem cần hoàn thiện thêm cái gì nhé

**Comment by manhcuong800** [comment]
Như vậy hiện tại là chúng mk đã cài đặt WordPress cho website rồi

**Comment by manhcuong800** [comment]
Chọn giao diện (theme) cho trang web nhìn chung cũng ok rồi

**Comment by manhcuong800** [comment]
Bây giờ a-e họp tập trung nốt cái phần quan trọng là cài đặt các WordPress plugin cơ bản cho nó.. Để tin tức các chức năng rồi font các hình ảnh theo ý của mk :))

**Comment by VuDinhDuy** [comment]
Chờ Quyền chốt ý tưởng thiết kế rồi bắt đầu triển. Ông tướng ấy bảo đang bận làm nốt cái bài C# môn Hệ thống trợ giúp quyết định để mai hay kia còn nộp bản xem trước.

**Comment by dangvietvu** [comment]
Ừ t cùng nhóm với Quyền môn hệ thống mấy hôm nọ hơi bận chút... Quyền đang thiết kế ý tưởng rồi.

**Comment by VuDinhDuy** [comment]
Vũ biết thao tác Photoshop có thể thiết kế cái banner không?

**Comment by VuDinhDuy** [comment]
Có theme rồi, giờ thiết kế banner, đặt menu, sắp xếp bố cục các thành phần trên trang chủ, tạo footer như đã thống nhất trong buổi họp nhé. Nếu chưa quen tuỳ chỉnh trên Wordpress thì Teamview với tôi.

**Comment by VuDinhDuy** [comment]
Thiết kế, sắp xếp giao diện trang chủ bằng WPBakery Page Builder nhé.
Những vùng hiển thị bài đăng mà ngang hàng với sidebar thì hiển thị bài theo 2 cột thôi.
Những vùng có thể hiển thị full chiều rộng thì ưu tiên hiển thị bằng slide để tiết kiệm diện tích mà vẫn trình diễn được nhiều bài.

**Comment by dangvietvu** [comment]
T đã làm một cái banner chính rồi nhưng màu sắc không phù hợp với theme lắm.Vậy t đẩy lên cái logo nhỏ phía trái thôi nhé

**Comment by dangvietvu** [comment]
Oke
