### ISSUE TITLE
Bước 4: Phát triển tính năng

### ISSUE THREAD

**Issue by VuDinhDuy** [VuDinhDuy/CNPM_BaiTapLon#7]

**Comment by VuDinhDuy** [comment]
Thực hiện: Đàm Mạnh Cường

**Comment by manhcuong800** [comment]
a-e trong bang lên tham khảo các cách sử dụng wp nhé để tạo trang web tổng hợp tin tức

**Comment by VuDinhDuy** [comment]
Cần tìm host wp trước.

**Comment by manhcuong800** [comment]
Thường thì 1 trang web tin tức sẽ có các tabbar về tin thể thao, thời sự trong nước và ngoài nước, dân trí, hình sự ...

**Comment by manhcuong800** [comment]
Nếu trình cao và có time thì cho thêm cái module quảng cáo, module thống kê và có thêm công cụ tìm kiếm...

**Comment by manhcuong800** [comment]
cố gắng cái phần search nó kiểu tìm kiếm lọc được nữa

**Comment by manhcuong800** [comment]
- Giúp người truy cập khai thác tối đa các thông tin trên website
- Xây dựng đường dẫn thân thiện với các công cụ tìm kiếm
- Về mặt tương thích: website có thể chạy tốt trên các trình duyệt thông dụng như Google chrome, CocCoc, Firefox, Opera…

**Comment by manhcuong800** [comment]
1 số chức năng bắt buộc có đó là: 
- Các mục tin (không giới hạn số mục, tự động phân trang)
Xem tin tức chi tiết
Tin mới hơn
Tin cũ hơn
In ấn tin
Lưu tin
Download tin ra file Word (cái này nếu có time sẽ cố gắng làm)
Bookmark tin vào các mạng xã hội
Phân loại tin theo Thẻ (Tag)
Xem tin theo ngày tháng

**Comment by manhcuong800** [comment]
wp chắc có phần bình luận đấy nên có phần bình luận tin tức thì càng ok

**Comment by manhcuong800** [comment]
Có ý kiến nhé trang chủ web của nhóm mk được thiết kế như thế này: bố cục hài hòa, định hướng cung cấp thông tin . Hệ thống menu cho phép bố trí linh hoạt các mục tin , nhóm tin và các phân nhóm tin... Hệ thống cho phép hiển thị tin mới nhất (cái này nếu a-e có thời gian thì nghiên cứu đk thì tốt ko thì từ từ rồi tính )

**Comment by VuDinhDuy** [comment]
Cường tìm và cài một số plugin hỗ trợ soạn thảo, SEO, tối ưu web nhé. Ví dụ như TinyMCE Advanced, Yoast SEO, WP Smush, WP Optimize... Các plugin hỗ trợ thiết kế thì theme có rồi.

**Comment by VuDinhDuy** [comment]
Lo phần tính năng đi, giao diện trang chủ Vũ chịu trách nhiệm.

**Comment by manhcuong800** [comment]
OK

Yoast SEO
Đây là 1 plugin hỗ trợ SEO mạnh mẽ giúp web tối ưu được các thẻ tiêu đề, mô tả,  tạo XML sitemap, hỗ trợ Social Media..

**Comment by manhcuong800** [comment]
Contact Form 7
Contact Form 7 là plugin hỗ trợ tạo form liên lạc từ đơn giản đến chuyên nghiệp. Ưu điểm của plugin liên hệ này là có tính tùy biến vượt trội.

**Comment by manhcuong800** [comment]
Advanced TinyMCE
Đây là plugin hỗ trợ những chức năng bị ẩn đi trong khung soạn thảo WordPress

**Comment by manhcuong800** [comment]
Responsive Lightbox by dFactory
 Tạo hiệu ứng lightbox khi click vào ảnh để xem ảnh lớn.

**Comment by manhcuong800** [comment]
WP Super Cache
  Tạo bộ nhớ đệm để tăng tốc website.

**Comment by manhcuong800** [comment]
Đây là các plugin cần thiết và uy tín trên wordpress.org có khá nhiều lượt tải. tôi nghĩ nên thế này thôi vì add nhiều plugin quá sẽ làm giảm tốc độ web chỉ cần những cái cần thiết cho web của chúng ta là ok rồi :))

**Comment by manhcuong800** [comment]
Phát triển nội dung
Tối ưu hóa SEO Onpage
Chỉnh sửa lại giao diện sao cho vừa ý
Vọc thêm nhiều tính năng hay của WordPress

**Comment by dangvietvu** [comment]
Nhiều Plug in thế,để t vào dùng thử ^^

**Comment by VuDinhDuy** [comment]
Chèn các liên kết mạng xã hội, preview Fanpage, đồng thời phát triển các tính năng mà theme sẵn có nữa nhé.
